css
mate-academy/react_uber-eats pull request #4
Opened 2019-08-20 05:47 UTC by nastyakpi1995

https://nastyakpi1995.github.io/react_uber-eats

2019-08-22 10:56 UTC, vkryvytskyi requested changes
https://www.loom.com/share/ad170ac56b63456c8513e52f221c5c95

2019-09-12 16:56 UTC, vkryvytskyi commented
https://www.loom.com/share/77bff8ba4f29483b83e1dfae50a7f35f

2019-09-12 17:12 UTC, vkryvytskyi commented
Хорошо поработала, Настя! Я в тебя верю!

2019-09-19 10:09 UTC, vpolets commented
https://www.loom.com/share/a3ff346aace3411ead99759d54e9d4a8

2019-10-07 13:58 UTC, nastyakpi1995 commented
> https://www.loom.com/share/a3ff346aace3411ead99759d54e9d4a8

на питання чому є зірочки а чому на інших картинках не має, то дані я не придумувала, і не доповнювала

2019-10-07 13:58 UTC, closed without merging